---
- name: Trying
  hosts: all
  vars:
    now: "{{ ansible_date_time.epoch|int * 1000}}"
    past: "{{ now|int - 86400000 }}" # 1h = 3600000   24h = 86400000
    commentuser: "Ansible Playbook"
    result: "200"
    payload:
     ProblemID: "{{ProblemID}}"
     ImpactedEntities: "{{impactedEntities}}"
  tasks:
    # Call remediation action
    # read the status of the remedy
    
    - name: Initiating the remedy action
      command: /bin/systemctl status sshd.service
      register: my_service_status
    
    - debug:
        msg: "{ (my_service_status.rc == 0) | ternary('Active', 'Down') }}"
