---
- name: Trying
  hosts: all
  vars:
    now: "{{ ansible_date_time.epoch|int * 1000}}"
    past: "{{ now|int - 86400000 }}" # 1h = 3600000   24h = 86400000
    commentuser: "Ansible Playbook"
    payload:
     ProblemID: "{{ProblemID}}"
     ImpactedEntities: "{{impactedEntities}}"
  tasks:
    - name: push comment to dynatrace
      debug:
       msg: "{{state}}"
      
